import config from '../../../config'

export const moduleName = 'EBG'
const prefix = `${config.appName}/${moduleName}`

const actionTypeBase = {
  ACTION_CHANGE_INN: `${prefix}/ACTION_CHANGE_INN`,

  LOAD_COMPANY_INFO: `${prefix}/LOAD_COMPANY_INFO`,
  LOAD_COMPANY_INFO_START: `${prefix}/LOAD_COMPANY_INFO_START`,
  LOAD_COMPANY_INFO_SUCCESS: `${prefix}/LOAD_COMPANY_INFO_SUCCESS`,
  LOAD_COMPANY_INFO_FAIL: `${prefix}/LOAD_COMPANY_INFO_FAIL`,

  LOAD_COMPANY_INFO_UL: `${prefix}/LOAD_COMPANY_INFO_UL`,
  LOAD_COMPANY_INFO_UL_START: `${prefix}/LOAD_COMPANY_INFO_UL_START`,
  LOAD_COMPANY_INFO_UL_SUCCESS: `${prefix}/LOAD_COMPANY_INFO_UL_SUCCESS`,
  LOAD_COMPANY_INFO_UL_FAIL: `${prefix}/LOAD_COMPANY_INFO_UL_FAIL`,

  CLEAR_COMPANY_INFO: `${prefix}/CLEAR_COMPANY_INFO`,

  GET_IDENTIFY_USER: `${prefix}/GET_IDENTIFY_USER`,
  GET_IDENTIFY_USER_START: `${prefix}/GET_IDENTIFY_USER_START`,
  GET_IDENTIFY_USER_SUCCESS: `${prefix}/GET_IDENTIFY_USER_SUCCESS`,
  GET_IDENTIFY_USER_FAIL: `${prefix}/GET_IDENTIFY_USER_FAIL`,

  DOWNLOAD_REPORT_FILE: `${prefix}/DOWNLOAD_REPORT_FILE`,

  UPDATE_SELECTED_USER_INFO: `${prefix}/UPDATE_SELECTED_USER_INFO`,
  UPDATE_SELECTED_USER_INFO_SUCCESS: `${prefix}/UPDATE_SELECTED_USER_INFO_SUCCESS`,
  UPDATE_SELECTED_USER_INFO_FAIL: `${prefix}/UPDATE_SELECTED_USER_INFO_FAIL`,

  GET_CROINFORM_USER_INFO: `${prefix}/GET_CROINFORM_USER_INFO`,
  GET_CROINFORM_USER_INFO_START: `${prefix}/GET_CROINFORM_USER_INFO_START`,
  GET_CROINFORM_USER_INFO_SUCCESS: `${prefix}/GET_CROINFORM_USER_INFO_SUCCESS`,
  GET_CROINFORM_USER_INFO_FAIL: `${prefix}/GET_CROINFORM_USER_INFO_FAIL`,

  ADD_USER_TO_CHECK_LIST: `${prefix}/ADD_USER_TO_CHECK_LIST`,

  GET_AFFILATES_LIST: `${prefix}/GET_AFFILATES_LIST`,
  GET_AFFILATES_LIST_START: `${prefix}/GET_AFFILATES_LIST_START`,
  GET_AFFILATES_LIST_SUCCESS: `${prefix}/GET_AFFILATES_LIST_SUCCESS`,
  GET_AFFILATES_LIST_FAIL: `${prefix}/GET_AFFILATES_LIST_FAIL`,

  GET_AFFILATES_UL: `${prefix}/GET_AFFILATES_UL`,
  GET_AFFILATES_UL_START: `${prefix}/GET_AFFILATES_UL_START`,
  GET_AFFILATES_UL_SUCCESS: `${prefix}/GET_AFFILATES_UL_SUCCESS`,
  GET_AFFILATES_UL_FAIL: `${prefix}/GET_AFFILATES_UL_FAIL`,

  GET_BLACK_STOP_LISTS: `${prefix}/GET_BLACK_STOP_LISTS`,
  GET_BLACK_STOP_LISTS_START: `${prefix}/GET_BLACK_STOP_LISTS_START`,
  GET_BLACK_STOP_LISTS_SUCCESS: `${prefix}/GET_BLACK_STOP_LISTS_SUCCESS`,
  GET_BLACK_STOP_LISTS_FAIL: `${prefix}/GET_BLACK_STOP_LISTS_FAIL`,

  GET_WHITE_STOP_LISTS: `${prefix}/GET_WHITE_STOP_LISTS`,

  LOAD_DIGEST_LIST: `${prefix}/LOAD_DIGEST_LIST`,
  LOAD_DIGEST_LIST_START: `${prefix}/LOAD_DIGEST_LIST_START`,
  LOAD_DIGEST_LIST_SUCCESS: `${prefix}/LOAD_DIGEST_LIST_SUCCESS`,
  LOAD_DIGEST_LIST_FAIL: `${prefix}/LOAD_DIGEST_LIST_FAIL`,

  LOAD_DIGEST_LIST_UL: `${prefix}/LOAD_DIGEST_LIST_UL`,
  LOAD_DIGEST_LIST_UL_START: `${prefix}/LOAD_DIGEST_LIST_UL_START`,
  LOAD_DIGEST_LIST_UL_SUCCESS: `${prefix}/LOAD_DIGEST_LIST_UL_SUCCESS`,
  LOAD_DIGEST_LIST_UL_FAIL: `${prefix}/LOAD_DIGEST_LIST_UL_FAIL`,

  ADD_RISK_FACTOR_IN_DIGEST_LIST: `${prefix}/ADD_RISK_FACTOR_IN_DIGEST_LIST`,

  ADD_RISK_FACTOR_UL_IN_DIGEST_LIST: `${prefix}/ADD_RISK_FACTOR_UL_IN_DIGEST_LIST`,
  ADD_RISK_FACTOR_UL_IN_DIGEST_LIST_START: `${prefix}/ADD_RISK_FACTOR_UL_IN_DIGEST_LIST_START`,
  ADD_RISK_FACTOR_UL_IN_DIGEST_LIST_SUCCESS: `${prefix}/ADD_RISK_FACTOR_UL_IN_DIGEST_LIST_SUCCESS`,
  ADD_RISK_FACTOR_UL_IN_DIGEST_LIST_FAIL: `${prefix}/ADD_RISK_FACTOR_UL_IN_DIGEST_LIST_FAIL`,

  EDIT_RISK_FACTOR_IN_DIGEST_LIST: `${prefix}/EDIT_RISK_FACTOR_IN_DIGEST_LIST`,

  EDIT_RISK_FACTOR_UL_IN_DIGEST_LIST: `${prefix}/EDIT_RISK_FACTOR_UL_IN_DIGEST_LIST`,
  EDIT_RISK_FACTOR_UL_IN_DIGEST_LIST_START: `${prefix}/EDIT_RISK_FACTOR_UL_IN_DIGEST_LIST_START`,
  EDIT_RISK_FACTOR_UL_IN_DIGEST_LIST_SUCCESS: `${prefix}/EDIT_RISK_FACTOR_UL_IN_DIGEST_LIST_SUCCESS`,
  EDIT_RISK_FACTOR_UL_IN_DIGEST_LIST_FAIL: `${prefix}/EDIT_RISK_FACTOR_UL_IN_DIGEST_LIST_FAIL`,

  DELETE_RISK_FACTOR_IN_DIGEST_LIST: `${prefix}/DELETE_RISK_FACTOR_IN_DIGEST_LIST`,

  DELETE_RISK_FACTOR_UL_IN_DIGEST_LIST: `${prefix}/DELETE_RISK_FACTOR_UL_IN_DIGEST_LIST`,
  DELETE_RISK_FACTOR_UL_IN_DIGEST_LIST_START: `${prefix}/DELETE_RISK_FACTOR_UL_IN_DIGEST_LIST_START`,
  DELETE_RISK_FACTOR_UL_IN_DIGEST_LIST_SUCCESS: `${prefix}/DELETE_RISK_FACTOR_UL_IN_DIGEST_LIST_SUCCESS`,
  DELETE_RISK_FACTOR_UL_IN_DIGEST_LIST_FAIL: `${prefix}/DELETE_RISK_FACTOR_UL_IN_DIGEST_LIST_FAIL`,

  ADD_RISK_FACTOR_FL_IN_DIGEST_LIST: `${prefix}/ADD_RISK_FACTOR_FL_IN_DIGEST_LIST`,
  ADD_RISK_FACTOR_FL_IN_DIGEST_LIST_START: `${prefix}/ADD_RISK_FACTOR_FL_IN_DIGEST_LIST_START`,
  ADD_RISK_FACTOR_FL_IN_DIGEST_LIST_SUCCESS: `${prefix}/ADD_RISK_FACTOR_FL_IN_DIGEST_LIST_SUCCESS`,
  ADD_RISK_FACTOR_FL_IN_DIGEST_LIST_FAIL: `${prefix}/ADD_RISK_FACTOR_FL_IN_DIGEST_LIST_FAIL`,

  EDIT_RISK_FACTOR_FL_IN_DIGEST_LIST: `${prefix}/EDIT_RISK_FACTOR_FL_IN_DIGEST_LIST`,
  EDIT_RISK_FACTOR_FL_IN_DIGEST_LIST_START: `${prefix}/EDIT_RISK_FACTOR_FL_IN_DIGEST_LIST_START`,
  EDIT_RISK_FACTOR_FL_IN_DIGEST_LIST_SUCCESS: `${prefix}/EDIT_RISK_FACTOR_FL_IN_DIGEST_LIST_SUCCESS`,
  EDIT_RISK_FACTOR_FL_IN_DIGEST_LIST_FAIL: `${prefix}/EDIT_RISK_FACTOR_FL_IN_DIGEST_LIST_FAIL`,

  DELETE_RISK_FACTOR_FL_IN_DIGEST_LIST: `${prefix}/DELETE_RISK_FACTOR_FL_IN_DIGEST_LIST`,
  DELETE_RISK_FACTOR_FL_IN_DIGEST_LIST_START: `${prefix}/DELETE_RISK_FACTOR_FL_IN_DIGEST_LIST`,
  DELETE_RISK_FACTOR_FL_IN_DIGEST_LIST_SUCCESS: `${prefix}/DELETE_RISK_FACTOR_FL_IN_DIGEST_LIST`,
  DELETE_RISK_FACTOR_FL_IN_DIGEST_LIST_FAIL: `${prefix}/DELETE_RISK_FACTOR_FL_IN_DIGEST_LIST`,

  GET_FSSP_INFO: `${prefix}/GET_FSSP_INFO`,
  GET_FSSP_INFO_START: `${prefix}/GET_FSSP_INFO_START`,
  GET_FSSP_INFO_SUCCESS: `${prefix}/GET_FSSP_INFO_SUCCESS`,
  GET_FSSP_INFO_FAIL: `${prefix}/GET_FSSP_INFO_FAIL`,

  GET_STOP_LISTS_UL_INFO: `${prefix}/GET_STOP_LISTS_UL_INFO`,
  GET_STOP_LISTS_UL_INFO_START: `${prefix}/GET_STOP_LISTS_UL_INFO_START`,
  GET_STOP_LISTS_UL_INFO_SUCCESS: `${prefix}/GET_STOP_LISTS_UL_INFO_SUCCESS`,
  GET_STOP_LISTS_UL_INFO_FAIL: `${prefix}/GET_STOP_LISTS_UL_INFO_FAIL`,

  GET_RISK_FACTORS_FL_INFO: `${prefix}/GET_RISK_FACTORS_FL_INFO`,
  GET_RISK_FACTORS_FL_INFO_START: `${prefix}/GET_RISK_FACTORS_FL_INFO_START`,
  GET_RISK_FACTORS_FL_INFO_SUCCESS: `${prefix}/GET_RISK_FACTORS_FL_INFO_SUCCESS`,
  GET_RISK_FACTORS_FL_INFO_FAIL: `${prefix}/GET_RISK_FACTORS_FL_INFO_FAIL`,

  GET_DOCUMENTS: `${prefix}/GET_DOCUMENTS`,
  GET_DOCUMENTS_START: `${prefix}/GET_DOCUMENTS_START`,
  GET_DOCUMENTS_SUCCESS: `${prefix}/GET_DOCUMENTS_SUCCESS`,
  GET_DOCUMENTS_FAIL: `${prefix}/GET_DOCUMENTS_FAIL`,

  GET_DOCUMENT_ITEM: `${prefix}/GET_DOCUMENT_ITEM`,
  GET_DOCUMENT_ITEM_START: `${prefix}/GET_DOCUMENT_ITEM_START`,
  GET_DOCUMENT_ITEM_SUCCESS: `${prefix}/GET_DOCUMENT_ITEM_SUCCESS`,
  GET_DOCUMENT_ITEM_FAIL: `${prefix}/GET_DOCUMENT_ITEM_FAIL`,

  UPDATE_EBG_SYNC_DATA: `${prefix}/UPDATE_EBG_SYNC_DATA`,
  UPDATE_EBG_SYNC_DATA_START: `${prefix}/UPDATE_EBG_SYNC_DATA_START`,
  UPDATE_EBG_SYNC_DATA_SUCCESS: `${prefix}/UPDATE_EBG_SYNC_DATA_SUCCESS`,
  UPDATE_EBG_SYNC_DATA_FAIL: `${prefix}/UPDATE_EBG_SYNC_DATA_FAIL`,

  TAKE_EBG_ITEM: `${prefix}/TAKE_EBG_ITEM`,
  TAKE_EBG_ITEM_START: `${prefix}/TAKE_EBG_ITEM_START`,
  TAKE_EBG_ITEM_SUCCESS: `${prefix}/TAKE_EBG_ITEM_SUCCESS`,
  TAKE_EBG_ITEM_FAIL: `${prefix}/TAKE_EBG_ITEM_FAIL`,

  RETURN_EBG_ITEM: `${prefix}/RETURN_EBG_ITEM`,
  RETURN_EBG_ITEM_START: `${prefix}/RETURN_EBG_ITEM_START`,
  RETURN_EBG_ITEM_SUCCESS: `${prefix}/RETURN_EBG_ITEM_SUCCESS`,
  RETURN_EBG_ITEM_FAIL: `${prefix}/RETURN_EBG_ITEM_FAIL`,

  ACCEPT_EBG_ITEM: `${prefix}/ACCEPT_EBG_ITEM`,
  ACCEPT_EBG_ITEM_START: `${prefix}/ACCEPT_EBG_ITEM_START`,
  ACCEPT_EBG_ITEM_SUCCESS: `${prefix}/ACCEPT_EBG_ITEM_SUCCESS`,
  ACCEPT_EBG_ITEM_FAIL: `${prefix}/ACCEPT_EBG_ITEM_FAIL`,

  UPDATE_HEADS: `${prefix}/UPDATE_HEADS`,
  LOCATION_CHANGE: `@@router/LOCATION_CHANGE`,
}

const constants: Readonly<typeof actionTypeBase> = actionTypeBase;
export default constants;