export const fieldsArr = [
  {search: "ShortNameRus", id: "name", title: "Сокрашеное наименование", data: ""},
  {search: "FullNameRus", id: "full_name", title: "Полное наименование", data: ""},
  {search: "INN", id: "inn", title: "ИНН", data: ""},
  {search: "OGRN", id: "ogrn", title: "ОГРН", data: ""},
  {search: "CompanyType", id: "company_type", title: "Тип компании", data: ""},
  {search: "DateFirstReg", id: "registration_date", title: "Дата регистрации", data: ""},
  {search: "Status-", id: "status", title: "Статус", data: ""},
  {search: "Address", id: "address", title: "Юридический адресс", data: ""},
  {search: "PhoneList-", id: "phone_list", title: "Список телефонов", data: ""},
  {search: "OKVED", id: "okved", title: "Основной ОКВЭД", data: ""},
  {search: "WorkersRange", id: "workers_range", title: "Численность персонала", data: ""},
  {search: "StaffNumbersFTS", id: "workers_range_fns", title: "Численность персонала по данным ФНС", data: ""},
  {search: "CharterCapital", id: "capital", title: "Уставной капитал", data: ""},
  {search: "IndexOfDueDiligence-", id: "index_of_due_diligence", title: "Индекс должносной осмотрительности", data: ""},
  {search: "PaymentIndex", id: "payment_index", title: "Индекс платежной дисциплины", data: ""},
  {search: "FailueScope", id: "failure_score", title: "Индекс финансового риска", data: ""},
  {search: "", id: "isponlit_proizvodstva", title: "Исполнительные производства", data: ""},
  {search: "", id: "fns", title: "ФНС", data: ""},
  {search: "", id: "sanctions", title: "Санкции", data: ""},
  {search: "", id: "precessors", title: "Предшедственники", data: ""},
  {search: "", id: "successors", title: "Приемники", data: ""},
  {search: "", id: "arbiter", title: "Арбитраж", data: ""},
  {search: "", id: "befenicials", title: "Бенефициары", data: ""},
  {search: "", id: "founders_fl", title: "Физические лица", data: ""},
  {search: "", id: "founders_ul", title: "Юридичекие лица", data: ""},
  {search: "", id: "heads", title: "Руководcтво", data: ""},
  {search: "", id: "management_companies", title: "Управляющие кампании", data: ""},
]