import config from '../../../config'
import { moduleName } from './index'

export const prefix = `${config.appName}/${moduleName}`

const actionTypeBase = {
  ACTION_CHANGE_INN: `${prefix}/ACTION_CHANGE_INN`,
  LOAD_COMPANY_INFO: `${prefix}/LOAD_COMPANY_INFO`,
  CLEAR_COMPANY_INFO: `${prefix}/CLEAR_COMPANY_INFO`,
  GET_IDENTIFY_USER: `${prefix}/GET_IDENTIFY_USER`,
  DOWNLOAD_REPORT_FILE: `${prefix}/DOWNLOAD_REPORT_FILE`,
  UPDATE_SELECTED_USER_INFO: `${prefix}/UPDATE_SELECTED_USER_INFO`,
  GET_CROINFORM_USER_INFO: `${prefix}/GET_CROINFORM_USER_INFO`,
  ADD_USER_TO_CHECK_LIST: `${prefix}/ADD_USER_TO_CHECK_LIST`,
  GET_AFFILATES_LIST: `${prefix}/GET_AFFILATES_LIST`,
  GET_AFFILATES_UL: `${prefix}/GET_AFFILATES_UL`,
  GET_BLACK_STOP_LISTS: `${prefix}/GET_BLACK_STOP_LISTS`,
  GET_WHITE_STOP_LISTS: `${prefix}/GET_WHITE_STOP_LISTS`,
  LOAD_DIGEST_LIST: `${prefix}/LOAD_DIGEST_LIST`,
  ADD_RISK_FACTOR_IN_DIGEST_LIST: `${prefix}/ADD_RISK_FACTOR_IN_DIGEST_LIST`,
  EDIT_RISK_FACTOR_IN_DIGEST_LIST: `${prefix}/EDIT_RISK_FACTOR_IN_DIGEST_LIST`,
  DELETE_RISK_FACTOR_IN_DIGEST_LIST: `${prefix}/DELETE_RISK_FACTOR_IN_DIGEST_LIST`,
  ADD_RISK_FACTOR_FL_IN_DIGEST_LIST: `${prefix}/ADD_RISK_FACTOR_FL_IN_DIGEST_LIST`,
  EDIT_RISK_FACTOR_FL_IN_DIGEST_LIST: `${prefix}/EDIT_RISK_FACTOR_FL_IN_DIGEST_LIST`,
  DELETE_RISK_FACTOR_FL_IN_DIGEST_LIST: `${prefix}/DELETE_RISK_FACTOR_FL_IN_DIGEST_LIST`,
  GET_FSSP_INFO: `${prefix}/GET_FSSP_INFO`,
  GET_STOP_LISTS_UL_INFO: `${prefix}/GET_STOP_LISTS_UL_INFO`,
  GET_RISK_FACTORS_FL_INFO: `${prefix}/GET_RISK_FACTORS_FL_INFO`,
  GET_DOCUMENTS: `${prefix}/GET_DOCUMENTS`,
  GET_DOCUMENT_ITEM: `${prefix}/GET_DOCUMENT_ITEM`,
  
  START: '_START',
  SUCCESS: '_SUCCESS',
  UPDATE: '_UPDATE',
  FAIL: '_FAIL',
}

const constants: Readonly<typeof actionTypeBase> = actionTypeBase;
export default constants;
